# site settings
title: Future of Life Foundation
subtitle: 
email: 
description: 
baseurl:  # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: 
city: 
state: 
zip_code: 
country: United States of America
phone: 

# social settings
500px_url:
facebook_url:
github_url: 
gitlab_url: 
googleplus_url:
instagram_url:
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
